name: "build"
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - 'Assets/**'
      - 'Unreal/**'
  push:
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - 'Assets/**'
      - 'Unreal/**'

jobs:
  build-mod:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, RelWithDebInfo, Release]

    steps:
    - uses: actions/checkout@v3
      with: 
        submodules: true

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64

    - name: Configure CMake
      working-directory: ${{github.workspace}}/Mod
      run: cmake -B build -S . -G "Visual Studio 16 2019" -A x64

    - name: echo MSBuild
      run: msbuild -version

    - name: Build project
      working-directory: ${{github.workspace}}/Mod/build
      run: msbuild /nologo /target:Build /property:Configuration=${{matrix.build_type}} INSTALL.vcxproj

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{matrix.build_type}}
        path: Mod/install/${{matrix.build_type}}
